# .air.toml

root = "/app"

[build]
cmd = "go build -race -o /app/tmp/main cmd/rater/main.go"
bin = "/app/tmp/main"
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["assets", "tmp", "vendor", "node_modules"]
# Exclude specific regular expressions.
exclude_regex = ["_test\\.go"]
delay = 1000
clear = true

[log]
time = true

[color]
# Customize each part's color. If no color found, use the raw app log.
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"
