all: false
dir: 'test/mocks'
filename: '{{.InterfaceName}}.go'
force-file-write: true
formatter: goimports
log-level: info
structname: '{{.InterfaceName}}'
pkgname: mocks
recursive: true
require-template-schema-exists: true
template: testify
template-schema: '{{.Template}}.schema.json'
packages:
  github.com/LiquidCats/rater/internal/app/port:
    config:
      all: true
