x-app-env: &app-env
  RATER_APP_PORT: 8080
  RATER_APP_PAIRS: "BTC_USD,BTC_EUR,ETH_USD,ETH_EUR"

  RATER_COINGATE_URL: "https://api.coingate.com/v2/rates/merchant"

  RATER_CEX_URL: "https://trade.cex.io/api/spot/rest-public/get_ticker"

  RATER_COINAPI_URL: "https://rest.coinapi.io/v1/exchangerate"
  RATER_COINAPI_SECRET: ""

  RATER_COINMARKETCAP_URL: "https://pro-api.coinmarketcap.com/v2/tools/price-conversion"
  RATER_COINMARKETCAP_SECRET: ""

  RATER_REDIS_ADDRESS: "redis:6379"
  RATER_REDIS_DB: 0

services:
  dev:
    build:
      dockerfile: Dockerfile.dev
      context: .
    working_dir: /app
    environment:
      <<: *app-env
    volumes:
      - .:/app

  cache:
    image: redis:alpine
    networks:
      - rater
    ports:
      - "6379:6379"

networks:
  rater:
    external: true
