FROM golang:1.24-alpine

WORKDIR /app

RUN apk add --no-cache build-base
RUN go install github.com/air-verse/air@latest

COPY go.mod go.sum ./
COPY . .

ENV CGO_ENABLED=1

RUN go mod download

CMD ["air", "-c", ".air.toml"]