version: "3.8"

services:
  dev:
    image: golang:alpine
    working_dir: /app
    tty: true
    networks:
      - rater
    ports:
      - "8080:8080"
    depends_on:
      - cache
    env_file: .env
    environment:
      GOPATH: "/go"
    volumes:
      - ~/.go:/go:ro
      - ./:/app:rw

  cache:
    image: redis:alpine
    networks:
      - rater
    ports:
      - "6379:6379"

networks:
  rater:
    external: true
