// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Rate struct {
	ID        int32
	Price     pgtype.Numeric
	Pair      string
	Provider  string
	CreatedAt pgtype.Timestamp
}
