// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: rates.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const saveRate = `-- name: SaveRate :one
insert into rates(price, pair, provider) values ($1, $2, $3) returning id, price, pair, provider, created_at
`

type SaveRateParams struct {
	Price    pgtype.Numeric
	Pair     string
	Provider string
}

func (q *Queries) SaveRate(ctx context.Context, arg SaveRateParams) (Rate, error) {
	row := q.db.QueryRow(ctx, saveRate, arg.Price, arg.Pair, arg.Provider)
	var i Rate
	err := row.Scan(
		&i.ID,
		&i.Price,
		&i.Pair,
		&i.Provider,
		&i.CreatedAt,
	)
	return i, err
}
