// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Pair struct {
	Symbol     string
	BaseAsset  string
	QuoteAsset string
	CreatedAt  pgtype.Timestamp
}

type Price5mOhlc struct {
	Bucket  interface{}
	Pair    string
	Open    interface{}
	High    interface{}
	Low     interface{}
	Close   interface{}
	Samples int64
}

type Provider struct {
	Name      string
	CreatedAt pgtype.Timestamp
}

type Rate struct {
	ID        int32
	Price     pgtype.Numeric
	Pair      string
	Provider  string
	Ts        pgtype.Timestamp
	CreatedAt pgtype.Timestamp
}
