// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

type Pair struct {
	Symbol     string
	BaseAsset  string
	QuoteAsset string
	CreatedAt  pgtype.Timestamp
}

type Provider struct {
	Name      string
	CreatedAt pgtype.Timestamp
}

type Rate struct {
	ID        int32
	Price     decimal.Decimal
	Pair      string
	Provider  string
	Ts        pgtype.Timestamp
	CreatedAt pgtype.Timestamp
}
