// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	entity "github.com/LiquidCats/rater/internal/app/domain/entity"

	mock "github.com/stretchr/testify/mock"
)

// ProviderErrRateMetric is an autogenerated mock type for the ProviderErrRateMetric type
type ProviderErrRateMetric struct {
	mock.Mock
}

// Inc provides a mock function with given fields: code, provider
func (_m *ProviderErrRateMetric) Inc(code int, provider entity.ProviderName) {
	_m.Called(code, provider)
}

// NewProviderErrRateMetric creates a new instance of ProviderErrRateMetric. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProviderErrRateMetric(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProviderErrRateMetric {
	mock := &ProviderErrRateMetric{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
