// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// ResponseTimeMetric is an autogenerated mock type for the ResponseTimeMetric type
type ResponseTimeMetric struct {
	mock.Mock
}

// Observe provides a mock function with given fields: route, start
func (_m *ResponseTimeMetric) Observe(route string, start time.Time) {
	_m.Called(route, start)
}

// NewResponseTimeMetric creates a new instance of ResponseTimeMetric. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewResponseTimeMetric(t interface {
	mock.TestingT
	Cleanup(func())
}) *ResponseTimeMetric {
	mock := &ResponseTimeMetric{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
