// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewTask creates a new instance of Task. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTask(t interface {
	mock.TestingT
	Cleanup(func())
}) *Task {
	mock := &Task{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Task is an autogenerated mock type for the Task type
type Task struct {
	mock.Mock
}

type Task_Expecter struct {
	mock *mock.Mock
}

func (_m *Task) EXPECT() *Task_Expecter {
	return &Task_Expecter{mock: &_m.Mock}
}

// Run provides a mock function for the type Task
func (_mock *Task) Run() {
	_mock.Called()
	return
}

// Task_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type Task_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
func (_e *Task_Expecter) Run() *Task_Run_Call {
	return &Task_Run_Call{Call: _e.mock.On("Run")}
}

func (_c *Task_Run_Call) Run(run func()) *Task_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Task_Run_Call) Return() *Task_Run_Call {
	_c.Call.Return()
	return _c
}

func (_c *Task_Run_Call) RunAndReturn(run func()) *Task_Run_Call {
	_c.Run(run)
	return _c
}
