name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.22"]
    env:
      RATER_PORT: "8080"
      RATER_BASE_CURRENCIES: "BTC"
      RATER_QUOTE_CURRENCIES: "USD"
      RATER_COINGATE_URL: "http://mocks:3001/coingate/v2/rates/merchant"
      RATER_COINAPI_URL: "http://mocks:3001/coinapi/v1/exchangerate"
      RATER_COINAPI_SECRET: "test1234"
      RATER_REDIS_ADDRESS: "cache:6379"
      RATER_REDIS_DB: "0"
      GOPATH: /home/runner/work/_temp/go
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Dependencies
        run: go get -d ./...

      - name: Run Tests
        run: go test -vet=off -v -race ./...